export const releases = [
  { version: '1.1.0', date: '2026-09-25', label: 'Stable update', title: 'Clearer activity and richer media files', groups: [
    { title: 'Downloader and history', items: ['Current downloading, converting, paused, and attention states now lead the Downloader screen.', 'Active work has search and status filters; completed items remain in the expanded History view.', 'History can filter video, audio, torrents, completed, and attention states while searching title, creator, album, and site.'] },
    { title: 'Media details', items: ['Audio filenames use Artist - Title when metadata is available; video filenames retain the source title.', 'Artwork, metadata, chapters, and cleaned details sidecars are enabled by default and configurable in Settings.', 'History shows source artwork, creator, album, duration, site, format, size, and attempts.'] },
    { title: 'Data integrity and updates', items: ['Cancelling a torrent no longer deletes downloaded payload or resume data, regardless of partial-file preference.', 'Website and application artwork now preserve source aspect ratios instead of stretching.', 'Installed builds check the official public GitHub release channel and can download and apply NSIS updates.'] }
  ] },
  { version: '1.0.0', date: '2026-09-18', label: 'Stable major update', title: 'Media and torrents, under your control', groups: [
    { title: 'Torrent downloads', items: ['Browser magnets and double-clicked torrent files open Add Torrent in installed dlME. Running instances receive new links without opening another app.', 'Choose a destination and files before downloading. All file categories are supported, including games, applications, archives, documents, and media.', 'Live progress, peer and upload statistics, piece verification, pause/resume, and restart recovery. Transfers stop at completion; uploading can occur during downloading.', 'No advertising, promotional game feeds, or embedded playback. Torrent files stay intact.'] },
    { title: 'Download fixes', items: ['Explicit progress output and buffering of both engine output streams fix the empty progress bar.', 'Preserved codec markers identify video-only streams; exact video selections include available audio, and output validation checks expected streams.', 'Checked Windows process-tree termination and pending/error feedback make Pause and Cancel accountable.', 'Late callbacks cannot complete or automatically restart a stopped job.'] },
    { title: 'Defaults and controls', items: ['New audio downloads default to Original / Best and Best quality. Explicit conversion formats remain available.', 'App sound muting applies immediately to active downloads and persists after restart.', 'Larger adjustable logs, expanded terminal view, and paginated queues keep controls reachable.'] },
    { title: 'Compatibility', items: ['Windows 10/11 x64; browser and torrent-file associations require the installed edition.', 'BitTorrent v1 and hybrid torrents with v1 metadata. Pure v2, torrent search, website scraping, embedded playback, and continued seeding are not included.', 'Existing profiles and downloads are preserved. Windows builds remain unsigned.'] }
  ] },
  { version: '0.9.1', date: '2026-09-11', label: 'Open Beta hotfix', title: 'Browser access that gets out of the way', groups: [
    { title: 'Fixed', items: ['Recognizes the Chrome cookie-database lock that previously stopped public downloads.', 'Automatically retries public media once without browser access when Chromium cookies are unavailable.', 'Applies the same recovery while analyzing a URL, before a download is created.'] },
    { title: 'Recovery & privacy', items: ['Manual Retry checks the selected browser again after you fully exit it.', 'Live logs show one clear recovery message instead of a traceback.', 'Local Windows profile names and credential-shaped values are removed from engine log messages.'] },
    { title: 'Guidance', items: ['Settings explains how to fully exit Chrome, Edge, or Brave, including background processes.', 'Firefox remains the recommended Windows option for authenticated downloads.'] }
  ] },
  { version: '0.9.0', date: '2026-09-10', label: 'Major beta update', title: 'A home for every download', groups: [
    { title: 'Major updates', items: ['New Files browser with category counts, search, sorting, pagination, and open-folder actions.', 'Complete supported-site directory from the installed yt-dlp engine, with search, filters, and page controls.', 'Organized download folders: Audio, Video, Image, Application, Zip, and Others.'] },
    { title: 'Improvements', items: ['Correct dlME branding and an explicit Open Beta version.', 'Wider live logs, tighter layouts, and simpler window and status bars.', 'In-app licenses and a local importer for your own legal documents.', 'Download defaults are available in Settings.'] },
    { title: 'Fixes', items: ['Exact-stream downloads now honor the selected output container.', 'Non-MP4 sources can be converted with FFmpeg; FFprobe checks the final MP4 container.', 'Files remain browsable after clearing history; missing outputs are marked clearly.'] }
  ] },
  { version: 'Earlier development builds', date: '2026-09-01', label: 'Foundation & minor updates', title: 'The download essentials', groups: [
    { title: 'Download engine', items: ['Pause, resume, retry, playlist selection, and local download history.', 'Bundled yt-dlp, FFmpeg, FFprobe, and Deno.', 'Unicode filename recovery and browser-session error guidance.'] },
    { title: 'Desktop experience', items: ['OLED, charcoal, and light themes with configurable accents.', 'Completion notifications, diagnostics export, tray mode, and onboarding.', 'Engine update checks, checksum verification, and rollback support.'] }
  ] }
]
