import { createRequire } from 'node:module'
import { mkdir, writeFile, readFile } from 'node:fs/promises'
import { resolve, join } from 'node:path'
import { execFileSync } from 'node:child_process'
import { createServer } from 'node:http'
import assert from 'node:assert/strict'

const require = createRequire(import.meta.url)
const { _electron: electron } = require(process.env.DLME_PLAYWRIGHT_PATH || 'playwright')
const release = JSON.parse(await readFile(resolve('package.json'), 'utf8')).version
const root = resolve(`verification/${release}`)
const profile = join(root, `profile-${Date.now()}`)
const downloads = join(profile, 'Downloads')
await mkdir(downloads, { recursive: true })
const sample = join(profile, 'sample.webm')
execFileSync(resolve('resources/engine/ffmpeg.exe'), ['-hide_banner', '-loglevel', 'error', '-f', 'lavfi', '-i', 'testsrc2=size=320x180:rate=15', '-f', 'lavfi', '-i', 'sine=frequency=440:sample_rate=44100', '-t', '2', '-c:v', 'libvpx-vp9', '-c:a', 'libopus', '-y', sample], { windowsHide: true })
const media = await readFile(sample)
const server = createServer((request, response) => { response.writeHead(200, { 'Content-Type': 'video/webm', 'Content-Length': media.length }); response.end(request.method === 'HEAD' ? undefined : media) })
await new Promise((done) => server.listen(0, '127.0.0.1', done))
const url = `http://127.0.0.1:${server.address().port}/sample.webm`
const errors = []
async function poll(page, predicate, timeout = 120000) {
  const deadline = Date.now() + timeout
  while (Date.now() < deadline) { if (await page.evaluate(predicate)) return; await new Promise((done) => setTimeout(done, 200)) }
  throw new Error('Timed out waiting for download completion')
}
let app
try {
  const env = { ...process.env, DLME_TEST_DATA: profile }; delete env.ELECTRON_RUN_AS_NODE
  app = await electron.launch({ executablePath: process.env.DLME_TEST_EXE || resolve('node_modules/electron/dist/electron.exe'), args: process.env.DLME_TEST_EXE ? [] : ['.'], cwd: process.cwd(), env, timeout: 60000 })
  const page = await app.firstWindow(); page.on('pageerror', (error) => errors.push(error.message))
  await page.waitForLoadState('load')
  await page.waitForFunction(() => !!window.dime)
  console.log('Loaded beta window')
  await page.evaluate(async (folder) => { await window.dime.updateSettings({ outputDirectory: folder, tutorialCompleted: true, engineAutoCheck: false, completionNotifications: false, completionSound: false }) }, downloads)
  await page.reload(); await page.getByRole('heading', { name: 'Download media', exact: true }).waitFor()
  assert.match(await page.locator('.version').innerText(), new RegExp(`dlME v${release.replaceAll('.', '\\.') }.*Open Beta`))
  assert.equal(await page.getByText('Download defaults', { exact: true }).count(), 0)
  assert.equal(await page.locator('.title-stats').count(), 0)
  assert.equal(await page.locator('.status-right').count(), 0)
  await page.screenshot({ path: join(root, 'downloader.png') })
  await page.getByRole('button', { name: 'Supported sites', exact: true }).click()
  await page.waitForFunction(() => document.querySelectorAll('.directory-entry').length > 0, null, { timeout: 60000 })
  const directory = await page.evaluate(() => window.dime.getSupportedSites())
  console.log(`Loaded ${directory.sites.length} official extractors`)
  assert.ok(directory.sites.length > 1500)
  const first = await page.locator('.directory-entry strong').first().innerText()
  await page.getByRole('button', { name: 'Next', exact: true }).click()
  assert.notEqual(await page.locator('.directory-entry strong').first().innerText(), first)
  await page.getByRole('searchbox', { name: 'Search sites' }).fill('youtube')
  await page.getByRole('combobox', { name: 'Status', exact: true }).selectOption('listed')
  assert.ok((await page.locator('.directory-entry strong').allTextContents()).every((name) => /youtube/i.test(name)))
  await page.screenshot({ path: join(root, 'supported-search.png') })
  await page.getByRole('searchbox', { name: 'Search sites' }).fill('')
  await page.getByRole('combobox', { name: 'Status', exact: true }).selectOption('broken')
  assert.ok((await page.locator('.site-status').allTextContents()).every((status) => status === 'Broken'))
  await page.getByRole('combobox', { name: 'Status', exact: true }).selectOption('all')
  await page.getByRole('combobox', { name: 'Type', exact: true }).selectOption('Collection')
  assert.ok((await page.locator('.directory-entry small').allTextContents()).every((text) => text.startsWith('Collection')))
  await page.getByRole('combobox', { name: 'Type', exact: true }).selectOption('all')
  await page.screenshot({ path: join(root, 'supported.png') })
  await page.getByRole('button', { name: 'Downloader', exact: true }).click()
  await page.getByRole('textbox', { name: 'Media URL' }).fill(url)
  await page.getByRole('button', { name: 'Analyze URL', exact: true }).click()
  await page.getByRole('button', { name: 'Start 1 download', exact: true }).waitFor({ timeout: 60000 })
  await page.getByRole('button', { name: /All formats and streams/ }).click()
  assert.ok(await page.locator('.format-list input').count(), 'Direct streams must be selectable')
  await page.locator('.format-list input').first().check()
  await page.getByRole('button', { name: 'Start 1 download', exact: true }).click()
  await poll(page, async () => (await window.dime.getHistory()).some((job) => ['completed', 'blocked'].includes(job.state)))
  const jobs = await page.evaluate(() => window.dime.getHistory())
  assert.equal(jobs[0].state, 'completed', JSON.stringify(jobs[0]))
  assert.ok(jobs[0].options.exactFormatId, 'Exact-stream conversion must be tested')
  assert.match(jobs[0].outputPath, /Video[\\/].*\.mp4$/)
  const probe = JSON.parse(execFileSync(resolve('resources/engine/ffprobe.exe'), ['-v', 'error', '-show_format', '-show_streams', '-of', 'json', jobs[0].outputPath], { windowsHide: true, encoding: 'utf8' }))
  assert.ok(probe.format.format_name.includes('mp4')); assert.ok(probe.streams.some((stream) => stream.codec_type === 'audio')); assert.equal(probe.streams.find((stream) => stream.codec_type === 'video').codec_name, 'h264')
  // Exercise audio extraction through the same main-process queue.
  await page.evaluate(async ({ url, downloads }) => { const analysis = await window.dime.analyzeUrl({ url }); await window.dime.enqueueDownload({ analysis, selectedEntryIds: [analysis.id], options: { kind: 'audio', quality: '1080', videoContainer: 'mp4', audioContainer: 'mp3', audioQuality: '192', outputDirectory: downloads } }) }, { url, downloads })
  await poll(page, async () => (await window.dime.getHistory()).filter((job) => job.state === 'completed').length === 2)
  const audioJob = (await page.evaluate(() => window.dime.getHistory())).find((job) => job.options.kind === 'audio')
  assert.match(audioJob.outputPath, /Audio[\\/].*\.mp3$/)
  for (let i = 0; i < 29; i++) await writeFile(join(downloads, 'Others', `Library fixture ${String(i).padStart(2, '0')}.txt`), 'dlME test fixture')
  await page.getByRole('button', { name: 'Files', exact: true }).click()
  await page.waitForFunction(() => document.querySelectorAll('.file-table tbody tr').length > 0)
  await page.getByRole('button', { name: 'Next', exact: true }).click()
  await page.getByRole('searchbox', { name: 'Search files' }).fill('sample')
  assert.equal(await page.locator('.file-table tbody tr').count(), 2)
  await page.screenshot({ path: join(root, 'files.png') })
  // Test real preload/main path authorization, with only the OS launcher stubbed.
  await app.evaluate(({ shell }) => { globalThis.__dlmeOpened = []; shell.openPath = async (path) => { globalThis.__dlmeOpened.push(path); return '' }; shell.showItemInFolder = (path) => { globalThis.__dlmeOpened.push(path) } })
  await page.getByRole('button', { name: `Open sample [sample].mp4`, exact: true }).click()
  await page.getByRole('button', { name: `Show sample [sample].mp4 in folder`, exact: true }).click()
  assert.equal((await app.evaluate(() => globalThis.__dlmeOpened)).length, 2)
  const escaped = await page.evaluate(async () => { try { await window.dime.openFile('C:\\Windows\\System32\\notepad.exe'); return false } catch { return true } })
  assert.equal(escaped, true)
  await page.evaluate(() => window.dime.clearHistory())
  await page.getByRole('button', { name: 'Refresh', exact: true }).click()
  await page.waitForFunction(() => document.querySelectorAll('.file-table tbody tr').length === 2)
  await page.getByRole('button', { name: 'About', exact: true }).click()
  await page.getByRole('button', { name: 'Licenses & documents', exact: true }).click()
  await page.locator('.legal-content').filter({ hasText: 'MIT License' }).waitFor()
  const legalFixture = join(profile, 'My beta terms.md'); await writeFile(legalFixture, '# My beta terms\n\nLocal document import test.')
  await app.evaluate(({ dialog }, file) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [file] }) }, legalFixture)
  await page.getByRole('button', { name: 'Add document', exact: true }).click()
  await page.locator('.legal-content').filter({ hasText: 'Local document import test.' }).waitFor()
  assert.ok((await page.evaluate(() => window.dime.getLegalDocuments())).some((doc) => doc.custom && doc.content.includes('Local document import test.')))
  assert.equal(await page.locator('.about-hero .eyebrow').count(), 0)
  await page.getByRole('button', { name: 'Changelog', exact: true }).click()
  assert.ok(await page.getByRole('heading', { name: 'Major updates', exact: true }).count())
  await page.screenshot({ path: join(root, 'changelog.png') })
  await page.getByRole('button', { name: 'Licenses & documents', exact: true }).click()
  await page.screenshot({ path: join(root, 'about.png') })
  await page.getByRole('combobox', { name: 'Legal document', exact: true }).selectOption({ label: 'THIRD PARTY NOTICES' })
  await page.evaluate(() => window.dime.updateSettings({ theme: 'light' })); await page.reload()
  await page.getByRole('button', { name: 'Supported sites', exact: true }).click()
  await page.waitForFunction(() => document.querySelectorAll('.directory-entry').length > 0)
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(900, 650))
  await page.waitForFunction(() => document.querySelectorAll('.directory-entry').length === 12)
  await page.screenshot({ path: join(root, 'supported-light-900.png') })
  assert.equal(await page.locator('.pager').evaluate((el) => el.getBoundingClientRect().bottom <= window.innerHeight - 30), true)
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth), false)
  assert.deepEqual(errors, [])
  const result = { passed: true, extractors: directory.sites.length, engine: directory.version, mp4: { codec: 'h264', audio: true, path: jobs[0].outputPath }, audio: audioJob.outputPath, rendererErrors: errors, profile }
  await writeFile(join(root, 'smoke-results.json'), JSON.stringify(result, null, 2))
  console.log(JSON.stringify(result, null, 2))
} finally { if (app) await app.close(); await new Promise((done) => server.close(done)) }
